### ISSUE TITLE
Build fails on python getNeuroML.py

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/PyNeuron-Toolbox#3]
I was trying to rebuild this locally (after adding matplotlib to the install list) and I got an error which I think is unrelated:  

```
------ Updating: NeuroML/org.neuroml.export -------
Creating a new directory: ../org.neuroml.export by cloning from GitHub
>>>  Executing: (git clone https://github.com/NeuroML/org.neuroml.export) in dir: ..
>>>  Executing: (git branch) in dir: ../org.neuroml.export
b'* master'
>>>  Executing: (git pull) in dir: ../org.neuroml.export
It's a Java repository, so installing using Maven...
>>>  Executing: (mvn install) in dir: ../org.neuroml.export
Error: 1
The command '/bin/sh -c sudo /opt/conda/bin/python getNeuroML.py' returned a non-zero code: 1
```

Did you ever have this problem?  Is the only way to debug it to get an interactive shell with an earlier image (say just the Ubuntu one it depends on) and then executing all the command until I get this error, and then debug from there?  Or is there some better way?

**Comment by rgerkin** [comment]
@russelljjarvis

**Comment by russelljjarvis** [comment]
Yes, I did have that exact problem. I think thats how I debugged it going into the interactive shell and seeing what stderr results. Or I may have just executed getNeuroML.py on my local machine with python3.

In my case the file getNeuroML.py is not python3 compliant, its the print statements they are python2.7 style.

So I edited the file and in a cloned version of the same NeuroML repository. I run the following line instead corresponding to my git remote for the new python3 compliant getNeuroML.py file:

RUN sudo git clone https://github.com/russelljjarvis/jNeuroML.git

As I understand it the pull request for the corresponding merge was accepted I requested to merge my python3 compliant version of getNeuroML perhaps the merge was only made into the dev branch. I will have to have a look.

#TODO change back to this repository, once pull request as accepted for python3 compliant code
#RUN sudo git clone https://github.com/NeuroML/jNeuroML

If this error is coming from my original code but from a month ago, its worth doing git pull on the repository that contains the Dockerbuild file as I made changes on the file up to relatively recently @rgerkin

**Comment by russelljjarvis** [comment]
Also are you sure that the real source of the error is not buried in the output from the dockerbuild 10 or 20 lines above the exit? Often it is.

**Comment by russelljjarvis** [comment]
Also it looks like you might be relying on the getNeuroML.py to install maven? 
As an alternative I ran RUN apt-get -y install maven #a few lines above.

**Comment by rgerkin** [comment]
I am running exactly the code that you have here, except that I added matplotlib to the install list.  I will follow the recommendations you gave above.
